version = 0.1
[default.deploy.parameters]
stack_name = "test"
resolve_s3 = true
s3_prefix = "test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "ModelId=\"anthropic.claude-instant-v1\" GoogleDriveSecretArn=\"arn:aws:secretsmanager:us-east-1:239576279337:secret:samapp-google-drive-secret-XciM5O\" KendraEdition=\"DEVELOPER_EDITION\""
image_repositories = []
