version = 0.1
[default.deploy.parameters]
stack_name = "test-rds-connector"
resolve_s3 = true
s3_prefix = "test-rds-connector"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "ModelId=\"anthropic.claude-instant-v1\" DatabaseHost=\"database-1.cr24egkisnaf.us-east-1.rds.amazonaws.com\" DatabaseName=\"medical\" TableName=\"PatientRecords\" SecretArn=\"arn:aws:secretsmanager:us-east-1:211125724964:secret:rds!db-bdecb746-229b-4748-9736-8e1d853f2331-OTlPwh\" ChangeDetectingColumns=\"DischargeDate, DateOfAdmission\" DocumentIdColumnName=\"PatientID\" DocumentDataColumnName=\"MedicalCondition\" VpcId=\"vpc-0175df0cd848e2df3\" SubnetIds=\"subnet-040c72f60df0798fe\" SecurityGroupIds=\"sg-01968d15b863a7abc\" KendraEdition=\"DEVELOPER_EDITION\""
image_repositories = []
